### ISSUE TITLE
Builds and base docker images for aarch64

### ISSUE THREAD

**Issue by matobet** [coord-e/magicpak#5]
Enjoying magicpak very much :heart: and I think it would be of great value to also provide builds as well as docker base images (for haskell/rust/...) (especially for Haskell in my case :-) ) also for the arm64 architecture. When developing for Raspberry Pi this could greatly help in producing smaller images that are easier to run on this resource constrained device.

**Comment by grosser** [comment]
somehow it worked locally on mac arm laptops, but failed in our CI
```
magicpak: cannot execute binary file: Exec format error
```

**Comment by coord-e** [comment]
How do you plan to build an arm64 image for your use case? (For example, are you building on an arm64 machine or are you cross-compiling in some way?) If you are cross-compiling, simply building an arm64 image may not be sufficient.

**Comment by grosser** [comment]
We are building on arm machines, not Cross Compiling.

**Comment by coord-e** [comment]
Initial implementation of arm64 support and image build CI is ready and I'll test them on Saturday

**Comment by grosser** [comment]
Thanks!

**Comment by coord-e** [comment]
v1.3.1 is out with AArch64 artifacts:
https://github.com/coord-e/magicpak/releases/tag/v1.3.1

**Comment by coord-e** [comment]
Closing by leaving #16 for the testing issue.
